classdef testUnpack < matlab.unittest.TestCase
  % TESTUNPACK Unit tests for unpack.m
  %
  % Tests {static, mobile} x {none, theta_hat, phi_hat, f_resamp}
  % and relevant combinations.
  %
  %   theta_hat: phase tracking only. h_hat drifts with motion.
  %     Unpack re-inserts phase only (no delay interpolation).
  %   phi_hat: phase + delay tracking. h_hat is static.
  %     Unpack re-inserts both phase and delay drift.
  %   f_resamp: bulk Doppler. Adds linear phase ramp + delay drift.
  %
  % Other m-files required: unpack.m
  % Subfunctions: place_taps, randsamples
  % Toolbox required: Signal Processing Toolbox (for resample).
  % MAT-files required: None.
  %
  % See also: unpack.m, replay.m
  %
  % Author: Zhengnan Li, Claude (Opus 4.6)
  % Email : uwa-channels@ofdm.link
  %
  % License: MIT
  %
  % Revision history:
  %   - Feb. 27, 2026: Initial release.

  properties (Constant)
    c = 1500;
  end

  properties (TestParameter)
    params = { ...
      ...
      ... %% === Static ===
      ...
      struct( ... % Case 1: Static, no tracking
      'label', 'static_none', ...
      'fc', 10e3, 'fs_delay', 8e3, 'fs_time', 20, ...
      'n_path', 8, 'Tmp', 10e-3, 'coeff', 1, ...
      'channel_time', 5, ...
      'tracking', 'none', 'has_f_resamp', false, ...
      'v_const', 0, 'v_amp', 0, 'n_cycles', 0), ...
      ...
      ... %% === Constant drift, theta_hat ===
      ...
      struct( ... % Case 2: theta_hat, moderate speed
      'label', 'drift_theta', ...
      'fc', 10e3, 'fs_delay', 8e3, 'fs_time', 100, ...
      'n_path', 8, 'Tmp', 10e-3, 'coeff', 1, ...
      'channel_time', 5, ...
      'tracking', 'theta', 'has_f_resamp', false, ...
      'v_const', -2, 'v_amp', 0, 'n_cycles', 0), ...
      ...
      struct( ... % Case 3: theta_hat, high speed
      'label', 'drift_theta_fast', ...
      'fc', 12e3, 'fs_delay', 10e3, 'fs_time', 100, ...
      'n_path', 8, 'Tmp', 15e-3, 'coeff', 1.5, ...
      'channel_time', 5, ...
      'tracking', 'theta', 'has_f_resamp', false, ...
      'v_const', 4, 'v_amp', 0, 'n_cycles', 0), ...
      ...
      ... %% === Constant drift, phi_hat ===
      ...
      struct( ... % Case 4: phi_hat, moderate speed
      'label', 'drift_phi', ...
      'fc', 10e3, 'fs_delay', 8e3, 'fs_time', 20, ...
      'n_path', 8, 'Tmp', 10e-3, 'coeff', 1, ...
      'channel_time', 5, ...
      'tracking', 'phi', 'has_f_resamp', false, ...
      'v_const', -2, 'v_amp', 0, 'n_cycles', 0), ...
      ...
      struct( ... % Case 5: phi_hat, high speed
      'label', 'drift_phi_fast', ...
      'fc', 12e3, 'fs_delay', 10e3, 'fs_time', 20, ...
      'n_path', 8, 'Tmp', 15e-3, 'coeff', 1.5, ...
      'channel_time', 5, ...
      'tracking', 'phi', 'has_f_resamp', false, ...
      'v_const', 4, 'v_amp', 0, 'n_cycles', 0), ...
      ...
      ... %% === f_resamp only ===
      ...
      struct( ... % Case 6: f_resamp, no tracking field
      'label', 'f_resamp_only', ...
      'fc', 15e3, 'fs_delay', 16e3, 'fs_time', 20, ...
      'n_path', 10, 'Tmp', 20e-3, 'coeff', 1, ...
      'channel_time', 5, ...
      'tracking', 'none', 'has_f_resamp', true, ...
      'v_const', 2, 'v_amp', 0, 'n_cycles', 0), ...
      ...
      ... %% === f_resamp + theta_hat (residual) ===
      ...
      struct( ... % Case 7: f_resamp handles bulk, theta_hat = 0
      'label', 'f_resamp_theta', ...
      'fc', 15e3, 'fs_delay', 16e3, 'fs_time', 100, ...
      'n_path', 10, 'Tmp', 20e-3, 'coeff', 1, ...
      'channel_time', 5, ...
      'tracking', 'theta', 'has_f_resamp', true, ...
      'v_const', 2, 'v_amp', 0.3, 'n_cycles', 3), ...
      ...
      ... %% === f_resamp + phi_hat (residual) ===
      ...
      struct( ... % Case 8: f_resamp handles bulk, phi_hat residual
      'label', 'f_resamp_phi', ...
      'fc', 15e3, 'fs_delay', 16e3, 'fs_time', 20, ...
      'n_path', 10, 'Tmp', 20e-3, 'coeff', 1, ...
      'channel_time', 5, ...
      'tracking', 'phi', 'has_f_resamp', true, ...
      'v_const', 2, 'v_amp', 0.3, 'n_cycles', 3), ...
      ...
      ... %% === Sinusoidal motion ===
      ...
      struct( ... % Case 9: sway only, theta_hat
      'label', 'sway_theta', ...
      'fc', 12e3, 'fs_delay', 10e3, 'fs_time', 100, ...
      'n_path', 8, 'Tmp', 15e-3, 'coeff', 1.5, ...
      'channel_time', 5, ...
      'tracking', 'theta', 'has_f_resamp', false, ...
      'v_const', 0, 'v_amp', 1.5, 'n_cycles', 4), ...
      ...
      struct( ... % Case 10: sway only, phi_hat
      'label', 'sway_phi', ...
      'fc', 12e3, 'fs_delay', 10e3, 'fs_time', 20, ...
      'n_path', 8, 'Tmp', 15e-3, 'coeff', 1.5, ...
      'channel_time', 5, ...
      'tracking', 'phi', 'has_f_resamp', false, ...
      'v_const', 0, 'v_amp', 1.5, 'n_cycles', 4), ...
      ...
      ... %% === Combined: AUV + sway ===
      ...
      struct( ... % Case 11: combined, theta_hat
      'label', 'combined_theta', ...
      'fc', 12e3, 'fs_delay', 10e3, 'fs_time', 100, ...
      'n_path', 8, 'Tmp', 15e-3, 'coeff', 1.5, ...
      'channel_time', 5, ...
      'tracking', 'theta', 'has_f_resamp', false, ...
      'v_const', 3, 'v_amp', 0.5, 'n_cycles', 3), ...
      ...
      struct( ... % Case 12: combined, phi_hat
      'label', 'combined_phi', ...
      'fc', 12e3, 'fs_delay', 10e3, 'fs_time', 20, ...
      'n_path', 8, 'Tmp', 15e-3, 'coeff', 1.5, ...
      'channel_time', 5, ...
      'tracking', 'phi', 'has_f_resamp', false, ...
      'v_const', 3, 'v_amp', 0.5, 'n_cycles', 3), ...
      };
  end

  methods (TestMethodSetup)
    function setRandomSeed(~)
      rng(1994);
    end
  end

  methods (Test)

    function testUnpackFunction(testCase, params)

      c = testCase.c;
      p = params;

      %% 1. Multipath geometry (single element)
      path_delay_0 = [0; sort(randsamples( ...
        (pi/3:p.Tmp*1e3) / 1e3, p.n_path - 1)).'];
      path_delay_0 = path_delay_0 - min(path_delay_0);

      path_gain = exp(-path_delay_0 * p.coeff ./ p.Tmp);
      c_p = path_gain .* exp(-1j * 2 * pi * p.fc * path_delay_0);

      %% 2. Motion model
      T_ch = p.channel_time;
      N_time = round(T_ch * p.fs_time);
      N_delay = round(T_ch * p.fs_delay);

      t_snapshots = (0:N_time-1) / p.fs_time;
      t_delay = (1:N_delay) / p.fs_delay;

      if p.n_cycles > 0
        omega_osc = 2*pi*p.n_cycles / T_ch;
      end

      % Cumulative delay at snapshot times
      dtau_snap = (p.v_const / c) * t_snapshots;
      if p.n_cycles > 0
        dtau_snap = dtau_snap ...
          - p.v_amp / (c * omega_osc) ...
          * (cos(omega_osc * t_snapshots) - 1);
      end

      % Cumulative phase at fs_delay rate
      %   phi(t) = -2*pi*fc * integral_0^t v(s)/c ds
      phi_const = -2*pi*p.fc * (p.v_const/c) .* t_delay;
      if p.n_cycles > 0
        phi_sin = p.fc * p.v_amp * T_ch / (c * p.n_cycles) ...
          * (cos(omega_osc * t_delay) - 1);
      else
        phi_sin = zeros(size(t_delay));
      end
      phi_full = phi_const + phi_sin;

      %% 3. Build h_hat
      L = ceil(p.fs_delay * p.Tmp * 1.5);
      has_motion = (p.v_const ~= 0) || (p.v_amp ~= 0);

      if strcmp(p.tracking, 'theta') && has_motion
        % theta_hat: delays drift in h_hat
        h_hat = zeros(L, 1, N_time);
        for k = 1:N_time
          h_hat(:, 1, k) = place_taps(L, 1, ...
            path_delay_0 + dtau_snap(k), ...
            c_p, p.Tmp, p.fs_delay);
        end
      else
        % phi_hat / none / static: h_hat is fixed
        h_hat_static = place_taps(L, 1, ...
          path_delay_0, c_p, p.Tmp, p.fs_delay);
        h_hat = repmat(h_hat_static, 1, 1, N_time);
      end

      %% 4. Determine tracking fields
      if p.has_f_resamp
        f_resamp = 1 / (1 + p.v_const / c);
        phi_tracking = phi_sin;  % residual only
      else
        f_resamp = [];
        phi_tracking = phi_full;
      end

      %% 5. Assemble channel struct
      channel = struct();
      channel.h_hat = h_hat;
      channel.params.fs_delay = p.fs_delay;
      channel.params.fs_time = p.fs_time;
      channel.params.fc = p.fc;
      channel.version = 1.0;

      switch p.tracking
        case 'theta'
          channel.theta_hat = phi_tracking;
        case 'phi'
          channel.phi_hat = phi_tracking;
        case 'none'
          % No tracking fields
      end

      if p.has_f_resamp
        channel.f_resamp = f_resamp;
      end

      %% 6. Unpack
      fs_time_out = p.fs_delay * 0.01;
      array_index = 1;
      unpacked = unpack(fs_time_out, array_index, channel, 0.3, 0.3);

      %% 7. Plot
      delay_axis = (0:size(unpacked, 1)-1) ./ p.fs_delay;
      time_axis = (0:size(unpacked, 3)-1) ./ fs_time_out;

      figure('Name', p.label, 'Position', [100 100 1200 600]);

      % --- Unpacked channel ---
      subplot(131);
      imagesc(delay_axis*1e3, time_axis, ...
        20*log10(squeeze(abs(unpacked(:, 1, :))).'), [-30, 0]);
      xlabel('Delay [ms]'); ylabel('Time [s]');
      title('Unpacked');
      colorbar;

      % --- h_hat (input) ---
      subplot(132);
      imagesc(delay_axis(1:L)*1e3, t_snapshots, ...
        20*log10(squeeze(abs(h_hat(:, 1, :))).'), [-30, 0]);
      xlabel('Delay [ms]'); ylabel('Time [s]');
      title('h_{hat} (input)');
      colorbar;

      % --- Speed from phase ---
      subplot(133);
      if strcmp(p.tracking, 'theta')
        phi_plot = channel.theta_hat;
      elseif strcmp(p.tracking, 'phi')
        phi_plot = channel.phi_hat;
      else
        phi_plot = zeros(1, N_delay);
      end
      if p.has_f_resamp
        phi_plot = phi_plot + (1/f_resamp - 1) * 2*pi*p.fc ...
          * (1:size(phi_plot, 2)) / p.fs_delay;
      end
      dphi = diff(phi_plot(1, :));
      v_inst = -dphi / (1/p.fs_delay * 2 * pi * p.fc) * c;
      t_speed = (0:length(v_inst)-1) / p.fs_delay;
      plot(t_speed, v_inst);
      xlabel('Time [s]'); ylabel('Speed [m/s]');
      title('Speed (from \phi)');
      grid on;

      sgtitle(p.label, 'Interpreter', 'none');
    end

  end
end


%% Helpers

function h = place_taps(L, M, delays, gains, Tmp, fs_delay)
h = zeros(L, M);
subs = round((delays + 0.2*Tmp) * fs_delay);
valid = (subs >= 1) & (subs <= L);
col_offset = (0:M-1) * L;
for m = 1:M
  v = valid(:, m);
  h(subs(v, m) + col_offset(m)) = gains(v, m);
end
end


function samples = randsamples(population, num)
rand_index = randperm(length(population));
samples = population(rand_index(1:num));
end
